version: '3'
services:
  backendserver:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - database
    command: >
      sh -c "sleep 5 && python manage.py migrate && gunicorn --workers=1 turfcoach_challenge.wsgi:application --bind 0.0.0.0:8000"
    environment:
      POSTGRES_DB: turfcoach_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: database
      WEATHER_API_KEY: YOU_API_KEY_HERE
  database:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: turfcoach_challenge