# Generated by Django 5.0.1 on 2024-01-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_name', models.CharField(max_length=100)),
                ('location', models.CharField(help_text="in format of 'city/country'", max_length=100)),
                ('turf_type', models.CharField(choices=[('natural', 'natural'), ('artificial', 'Artificial'), ('hybrid', 'hybrid')], max_length=12)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_scheduled_maintenance', models.DateField(blank=True, null=True)),
                ('current_condition', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_will_it_rain', models.BooleanField()),
                ('location', models.CharField(help_text='in format of city/country', max_length=100)),
            ],
            options={
                'unique_together': {('date', 'location')},
            },
        ),
    ]
